language: csharp
solution: src/NeoCity.sln
install:
- nuget restore src/NeoCity.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=ReleaseUnix src/NeoCity.sln
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/SharedTests/bin/ReleaseUnix/SharedTests.dll
matrix:
  include:
  - dotnet: 1.0.1
    mono: none
    dist: trusty
    env: DOTNETCORE=1
  - mono: latest
deploy:
  provider: releases
  api_key:
    secure: L8sXG7TsqJGrb0/hZnFST/h5nv22Fj2YOyWRJmonXcbT2+dzasESU9HaJOU6HKGtj83/J7pePM6RFp27jOtRcUzhevRHRLee/lMoLPfFJqhZGMJT97tXVgSjQOOM757eT7nWFCVl0897UszXLr0H5sZtBvOqh8Y6r6Ty1qOYVe62aCTf5D9a+Pi6kA1pLNIbxHtaSrPc6GLpGbt1wzVJHcPlZYDe2dz8RirWGa81H8ulxyg01UpziNHjEb7y0vETNjf3YTk7bVua2QOkeuzvDlFLPlczlLto+UbzEg97uaPVgK2wd89YQ4FCDsV5k1jhqwKuLEvbLN1DAxztDl/Qk9GHUknRGr16GApd1f7ngLMlK/WKCo++0HPHgTCginROWrMisFDg2gNruQCf8HHwgqIEGQtquJkTLLaFgEFa2dyuaUGfvw/qL9T8qwO/FyjmHMocBEGn9PstanUpo4KIb6lxQ0GHekmvYhcPxc65qw4CUYABm7Sk+Ey8SnrKd6pEXsUNtnnF7+0TvtBbYRkxOeDOJw6vArg0rm7bhtz3jOW0np/y4XRKLczGhv+9dcGoUU4vSK82lt7u1Bh+lng6QTduzahYjVceM3UW40fn9zI9qmQLWIRFl75DPBfN+onVxkxD4Kx933VB7hGajVcKj6ChZmxmrxF3wkYb/i3oByk=
  file_glob: true
  file: bin/ReleaseUnix/*
  on:
    repo: exmex/DCNC
